name: typedefx_generator
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  analyzer: ^1.0.0
  build: ^2.0.0
  build_config: ^0.4.2
  meta: ^1.3.0
  source_gen: ^1.0.0
  typedefx:
    path: ../typedefx

dev_dependencies:
  # json_serializable: ^4.0.0
  # json_annotation: ^4.0.0
  build_test: ^2.0.0
  build_runner: ^1.10.3
  test: ^1.16.5
  # matcher: ^0.12.10
  source_gen_test: ^1.0.0